/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/common/AppFooter.vue')['default']
    BottomBar: typeof import('./components/common/BottomBar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InnerNavBar: typeof import('./components/common/InnerNavBar.vue')['default']
    Loader: typeof import('./components/common/Loader.vue')['default']
    Navbar1: typeof import('./components/common/Navbar1.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scrolldown: typeof import('./components/common/Scrolldown.vue')['default']
    SearchBar: typeof import('./components/common/SearchBar.vue')['default']
    SidebarMenuHome: typeof import('./components/common/SidebarMenuHome.vue')['default']
    TeacherBot: typeof import('./components/common/TeacherBot.vue')['default']
  }
}
